spring.application.name=render


#For Render

spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT}
gemini.api-key=AIzaSyAqolBFOvz6Nutf3RF5r2WuaJwInVmJ_zs


#For Local
#
#spring.data.mongodb.uri=mongodb://localhost:27017/users
#server.port=8080