spring.application.name=render


#For Render

spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT}


#For Local
#
#spring.data.mongodb.uri=mongodb+srv://Yashraj:dtCtMFFyd6axqR2z@render-cluster.j9tc7pn.mongodb.net/users?retryWrites=true&w=majority&tls=true
#server.port=8080